# Generated by Django 4.0.5 on 2022-06-24 06:07

from django.db import migrations, models
import pictureapi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PictureModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='image/default.jpg', upload_to=pictureapi.models.upload_to)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
